//
//  TriviaData.swift
//  TriviaGame
//
//  Created by Alex Paul on 10/21/19.
//  Copyright © 2019 Alex Paul. All rights reserved.
//

import Foundation

// https://www.usefultrivia.com/movie_trivia/
// https://www.factmonster.com/take-quiz/new-york-city
struct Trivia {
  static let data: [[String: Any]] = [
    // movie
    ["question": "What is the highest grossing movie of all time?",
     "correctAnswer": "d",
     "choices": "a. Avatar\nb. Titanic\nc. Dark Knight\nd. Avenger Endgame",
     "fact": "Surpassed James Cameron's Avatar in 2019 with a gross box office number of $2.79 billion.",
     "triviaType": "movieTrivia"],
    ["question": "What is the longest movie ever made?",
     "correctAnswer": "a",
     "choices": "a. The cure for insomnia\nb. Hamlet\nc. The Stand\nd. Dances with Wolves",
     "fact": "he Cure for Insomnia (1987) is the longest movie ever made at a total running\ntime of 85 hours (5,220 min). It premiered in its entirety at The School Of The Art Institute in Chicago, Illinois\nfrom January 31 to February 3, 1987, in one continuous showing.",
     "triviaType": "movieTrivia"],
    ["question": "What was the first movie by Pixar to receive a rating higher than G in the United States?",
     "correctAnswer": "c",
     "choices": "a. Finding Nemo\nb. Monsters Inc.\nc. The Incredibles\nd. Toy Story",
     "fact": "The Incredibles received a PG rating for \"action violence\".",
     "triviaType": "movieTrivia"],
    ["question": "In The Wizard of Oz (1939), what was used to simulate snow during the poppy scene?",
     "correctAnswer": "a",
     "choices": "a. Asbestos\nb. Powdered Sugar\nc. Coconut Flakes\nd. Cornflakes",
     "fact": "The snow wasn't the only asbestos-laden element of production: \nThe Wicked Witch's broom was made of asbestos, as was the Scarecrow's entire outfit.",
     "triviaType": "movieTrivia"],
    ["question": "What movie popularized the phrase: \"May the Force be with you\"?",
     "correctAnswer": "d",
     "choices": "a. E.T\nb. The Matrix\nc. Star Trek\nd. Star Wars",
     "fact": "In the Star Wars movies, \"May the Force be with you\" was a phrase \nused to wish good luck or good will. The phrase was often used as individuals\nparted ways or in the face of an impending challenge.",
     "triviaType": "movieTrivia"],
    
    // music
    ["question": "What pop singer is known as \"The Material Girl\"?",
     "correctAnswer": "b",
     "choices": "a. Taylor Swift\nb. Madonna\nc. Britney Spears\nd. Christina Aguilera",
     "fact": "Madonna became known as \"The Material Girl\" after her hit single of\nthe same name hit the charts in 1984. She hates it, claiming she\nwould never have done the song if she knew the name would stick.",
     "triviaType": "musicTrivia"],
    ["question": "What singer holds the world record for most words in a hit single?",
     "correctAnswer": "c",
     "choices": "a. Kanye West\nb. Busta Rhymes\nc. Eminem\nd. 50 Cents",
     "fact": "The Detroit rapper achieved a world record with \"Rap God\".\nThe six-minute track contains 1,560 words which means that\nEminem is rapping a tongue-twisting 4.28 words per second.",
     "triviaType": "musicTrivia"],
    
    // sports
    ["question": "Who was the only person in NBA history to be named Most Valuable Player, Coach of the Year, and Executive of the Year?",
     "correctAnswer": "a",
     "choices": "a. Larry Bird\nb. Michael Jordan\nc. Bill Russel\nd. Phil Jackson",
     "fact": "Drafted into the NBA sixth overall by the Boston Celtics in\n1978, Larry Bird played his entire professional career for\nBoston, winning three NBA championships and two NBA\nFinals MVP awards. He then served as head coach of the Indiana Pacers\nfrom 1997 to 2000, and in 2003 assumed the role of president of basketball\noperations for the Pacers.",
     "triviaType": "sportsTrivia"],
    
    // nyc
    ["question": "The New York Aquarium is located in which New York City borough?",
     "correctAnswer": "c",
     "choices": "a. Queens\nb. Bronx\nc. Brooklyn\nd. Manhattan",
     "fact": "In 1896, the New York Aquarium first opened in Battery Park, Manhattan,\nbut it was moved to its current location in Brooklyn in 1957.",
     "triviaType": "nycTrivia"],
    ["question": "What stadium located in Flushing, Queens, is home to the New York Mets?",
     "correctAnswer": "d",
     "choices": "a. Yankee Stadium\nb. Ebbets Field\nc. Polo Grounds\nd. Shea Stadium",
     "fact": "The first game played at Shea Stadium in 1964 was between\nthe New York Mets and the Pittsburgh Pirates in front of 48,736 fans.",
     "triviaType": "nycTrivia"],
    
    // second grade math
    ["question": "Which shows a way to find the difference?\n15 - 6 = ____",
    "correctAnswer": "a",
    "choices": "a. 10 - 1 = 9\nb. 10 - 4 = 6\nc. 10 - 5 = 5\nd. 10 - 6 = 4",
    "fact": "10 - 1 = 9 has the same result as 15 - 6 = 9",
    "triviaType": "secondGradeMath",
    "level": "hard"],
    ["question": "Which shows a way to find the sum?\n8 + 5 = ____",
    "correctAnswer": "a",
    "choices": "a. 10 + 3 = 13\nb. 10 + 5 = 15\nc. 10 + 6 = 16\nd. 10 + 8 = 18",
    "fact": "8 + 5 = 13 has the same result as 10 + 3 = 13",
    "triviaType": "secondGradeMath",
    "level": "3"],
    ["question": "Chris has 3 rows of plates.\nThere are 5 plates in each row.\nHow many plates are there in all?",
    "correctAnswer": "d",
    "choices": "a. 3 + 3 + 3 = 9\nb. 3 + 3 + 5 = 11\nc. 4 + 4 + 4 = 12\nd. 5 + 5 + 5 = 15",
    "fact": "",
    "triviaType": "secondGradeMath",
    "level": "3"],
    ["question": "Sally counts 7 stars. Mike\ncounts 1 more star than Sally.\nHow many stars do they count\nin all?\n____stars.",
    "correctAnswer": "15",
    "choices": "",
    "fact": "7 stars for Sally + (7 stars + 1 star for Mike)\n7 + 8 = 15 stars counted in all\n",
    "triviaType": "secondGradeMath",
    "level": "3"],
    ["question": "Phillip puts 5 pencils on each\ndesk. How many pencils does\nPhillip put on 4 desks?/nDraw to show what you did.\n____pencils.",
      "correctAnswer": "20",
      "choices": "",
      "fact": "Desk1: ✏️✏️✏️✏️✏️\nDesk2: ✏️✏️✏️✏️✏️\nDesk3: ✏️✏️✏️✏️✏️\nDesk4: ✏️✏️✏️✏️✏️\n",
      "triviaType": "secondGradeMath",
      "level": "3"],
    ["question": "Tania has 3 rows of stickers.\nThere are 4 stickers in each\nrow. How many stickers does\nTania have in all?\n____stickers.",
    "correctAnswer": "12",
    "choices": "",
    "fact": "Row 1: 🦊 🐻 🐝 🦖\nRow 2: 🦊 🐻 🐝 🦖\nRow 3: 🦊 🐻 🐝 🦖\n",
    "triviaType": "secondGradeMath",
    "level": "3"],
    ["question": "Abe needs 11 football stickers. He has 2 stickers.\nHow many more stickers does Abe need?\n____stickers\nShow how you solved the problem.",
    "correctAnswer": "9",
    "choices": "",
    "fact": "Row 1: 🦊 🐻 🐝 🦖\nRow 2: 🦊 🐻 🐝 🦖\nRow 3: 🦊 🐻 🐝 🦖\n",
    "triviaType": "secondGradeMath",
    "level": "3"],
    ["question": "What is the sum?\n7 + 3",
       "correctAnswer": "d",
       "choices": "a. 7\nb. 8\nc. 9\nd. 10\n",
       "fact": "",
       "triviaType": "secondGradeMath",
       "level": "1"],
    ["question": "What is the difference?\n\n14 - 9 = ____",
          "correctAnswer": "c",
          "choices": "a. 23\nb. 9\nc. 5\nd. 3\n",
          "fact": "",
          "triviaType": "secondGradeMath",
          "level": "1"],
    ["question": "Mia has 8 magnets. Rob has\n7 magnets.\n\nWhich doubles fact can you\nuse to find how many magnets\nthey have is all?\n",
          "correctAnswer": "b",
          "choices": "a. 9 + 9 = 18\nb. 8 + 8 = 16\nc. 6 + 6 = 12\nd. 5 + 5 = 10\n",
          "fact": "",
          "triviaType": "secondGradeMath",
          "level": "3"],
    ["question": "Sharon puts 3 oranges in each\nbag. There are 5 bags. How\nmany oranges are there\nis all?\n",
             "correctAnswer": "c",
             "choices": "a. 8\nb. 12\nc. 15\nd. 18\n",
             "fact": "Bag 1: 🍊 🍊 🍊\nBag 2: 🍊 🍊 🍊\nBag 3: 🍊 🍊 🍊\nBag 4: 🍊 🍊 🍊\nBag 5: 🍊 🍊 🍊\n",
             "triviaType": "secondGradeMath",
             "level": "3"],
    ["question": "Janie has 4 toy dogs, 3 toy\ncats, and 3 toy bears. How\nmany toys does Janie have\nin all?\n",
                "correctAnswer": "d",
                "choices": "a. 6\nb. 7\nc. 9\nd. 10\n",
                "fact": "4 + 3 + 3 = 10 toys in all",
                "triviaType": "secondGradeMath",
                "level": "1"],
    ["question": "What is the sum?\n\n5 + 6 + 7 = ____\n",
                "correctAnswer": "d",
                "choices": "a. 11\nb. 13\nc. 16\nd. 18\n",
                "fact": "",
                "triviaType": "secondGradeMath",
                "level": "1"],
    ["question": "There are 7 ducks on a pond.\nSome more ducks joined them.\nThen there were 12 ducks on\nthe pond. How many ducks\njoined them?\n",
                  "correctAnswer": "b",
                  "choices": "a. 4\nb. 5\nc. 12\nd. 19\n",
                  "fact": "12 - 7 = 5 ducks joined.",
                  "triviaType": "secondGradeMath",
                  "level": "2"],
    ["question": "What is the missing number in\nthe related subraction fact?\n\n6 + 5 = 11\n11 - 6 = ____\n",
                     "correctAnswer": "c",
                     "choices": "a. 11\nb. 6\nc. 5\nd. 4\n",
                     "fact": "",
                     "triviaType": "secondGradeMath",
                     "level": "1"],
    ["question": "Ally has 12 dimes. Louis has 5\ndimes. How many more dimes\ndoes Ally have than Louis?\n",
                     "correctAnswer": "a",
                     "choices": "a. 7\nb. 8\nc. 9\nd. 17\n",
                     "fact": "12 - 5 = 7 (Ally has 7 more dimes than Louis)",
                     "triviaType": "secondGradeMath",
                     "level": "2"],
    
    
    ["question": "Glenn has 6 markers in his\ndesk. He has 1 marker in his\npocket. How many markers\ndoes Glenn have\n____markers\n",
                       "correctAnswer": "7",
                       "choices": "",
                       "fact": "6 + 1 = 7 markers",
                       "triviaType": "secondGradeMath",
                       "level": "2"],
    
  ]
}
